.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. otherb_qt test_otherb_qt
clean: FORCE
	$(MAKE) -C .. otherb_qt_clean test_otherb_qt_clean
check: FORCE
	$(MAKE) -C .. test_otherb_qt_check
otherb-qt otherb-qt.exe: FORCE
	 $(MAKE) -C .. otherb_qt
